apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website
spec:
  type: LoadBalancer
  selector:
    app: website
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80