apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
          name: mariadb-port
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-user-password
        - name: MARIADB_USER
          value: ecomuser
        - name: MARIADB_DATABASE
          value: ecomdb
        volumeMounts:
        - name: mariadb-pv 
          mountPath: /var/lib/mysql
        - name: mariadb-config 
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      - name: mariadb-config
        configMap:
          name: mariadb-configmap